-- Create the table for shifts
create table public.shifts (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null,
  start_time text not null,
  end_time text not null,
  salary numeric,
  type text check (type in ('Tutor', 'MyBasket', 'Other')),
  description text,
  hourly_rate numeric,
  location text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.shifts enable row level security;

-- Create a policy that allows anyone to read/write (since we are not using auth for now)
-- WARNING: In a real production app with multiple users, you would restrict this to authenticated users.
create policy "Enable all access for all users" on public.shifts
for all using (true) with check (true);
